---
- name: Pull Docker Image from Docker Hub and Run Container
  hosts: localhost
  connection: local
  remote_user: manasi
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "manasip44/calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started

    - name: Run Docker Container
      docker_container:
        name: calculator
        image: "manasip44/calculator"
        state: started
      register: docker_container_result

    - name: Display Docker Container Result
      debug:
        var: docker_container_result
